package main

import (
	"fmt"
	"mapreduce"
	"os"
	"strconv"
	"unicode"
)

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func mapF(filename string, contents string) []mapreduce.KeyValue {
	// Your code here (Part II).

	var result []mapreduce.KeyValue
	prevStart := 0
	isLetter := false
	for idx, runeC := range contents {
		//fmt.Println("file %s, idx %d, rune %s", filename, idx, string(runeC))
		if unicode.IsLetter(runeC) {
			if !isLetter {
				prevStart = idx
			}
			isLetter = true
			continue
		}
		if !isLetter {
			isLetter = false
			continue
		}
		kv := mapreduce.KeyValue{contents[prevStart:idx], "1"}
		result = append(result, kv)
		//fmt.Println(kv)
		isLetter = false
	}
	return result
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func reduceF(key string, values []string) string {
	// Your code here (Part II).
	//fmt.Println("reduce: %s, %v", key, values)
	res := 0
	for _, cnt := range values {
		tmpCnt, err := strconv.Atoi(cnt)
		if err != nil {
			// todo
			fmt.Println("the err key %s, error %v", key, cnt, err)
		}
		res += tmpCnt
	}
	return strconv.Itoa(res)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
